version: '2'
services:

  dev:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 8080:8080
    # environment:
      # - DBT_HOST=${CLICKHOUSE_HOST}
      # - DBT_USER=admin
      # - DBT_PASSWORD=${CLICKHOUSE_PASSWORD}
      